### PR TITLE
Make `indexstoredb_symbol_location_timestamp` and `indexstoredb_timestamp_of_latest_unit_for_file` return nanoseconds instead of seconds

### PR DESCRIPTION
**Pull request by ahoppen**
rdar://126581823

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/sourcekit-lsp/pull/1188

@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Review by bnbarham — APPROVED** [review]

**Pull request merged**
