### PR TITLE
Database: correct the PID recording on Windows

### PR DESCRIPTION
**Pull request by compnerd**
`GetCurrentProcess` provides a process _handle_ (which for current
process is a pseudo-handle of `-1`).  Use `GetCurrentProcessId` which is
the moral equivalent to `getpid`.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Review by benlangmuir — COMMENTED** [review]
There's another call in `cleanupDiscardedDBsImpl` that probably needs to be updated to match

**Comment by compnerd** [comment]
@swift-ci please test

**Review by benlangmuir — APPROVED** [review]

**Review by akyrtzi — APPROVED** [review]

**Comment by compnerd** [comment]
hmm, this doesn't build on Windows :/

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
