### PR TITLE
Adopt ArgumentParser for the command-line tool

### PR DESCRIPTION
**Pull request by natecook1000**
This adopts the new `ArgumentParser` library for parsing command-line arguments.

### CODE REVIEW

**Comment by benlangmuir** [comment]
Hey @natecook1000 this looks really nice.  My preference would be to wait until SwiftPM adopts ArgumentParser, then adopt it in sourcekit-lsp and indexstore-db.  Until we're using it across the board in sourcekit-lsp+swiftpm, introducing a new dependency creates integration headaches for us that outweigh the benefits in this case (since this is only a tiny test executable).

I'd be happy to keep this PR open until we're ready to take it.  Thanks again for the PR

**Comment by natecook1000** [comment]
@benlangmuir Sounds like a good plan! I'll ping back when we've landed the SwiftPM change.

**Comment by Aekewu** [comment]
App

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create the pull request with `main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
