### PR TITLE
[test] Put shared test projects INPUTS into bundle resources 

### PR DESCRIPTION
**Pull request by benlangmuir**
This avoids depending on the absolute path to the INPUTS and allows looking it up at run time even if the tests have moved.

This required updating to tools version 5.3 to use resource support, and adding several "excludes" to the Package.swift for files that are not recognized by swiftpm.

### CODE REVIEW

**Comment by benlangmuir** [comment]
https://github.com/apple/sourcekit-lsp/pull/322
@swift-ci please smoke test

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#322
@swift-ci please smoke test Linux

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#322
@swift-ci please smoke test Linux

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#322
@swift-ci please smoke test Linux

**Review by akyrtzi — APPROVED** [review]

**Comment by benlangmuir** [comment]
apple/sourcekit-lsp#322
@swift-ci please smoke test

**Pull request merged**
